"""Simple Flask front-end for generating Chris's Conductor Agent daily schedule."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from flask import Flask, redirect, render_template, request, url_for

import conductor_schedule

app = Flask(__name__)


def _list_from_text(value: str) -> List[str]:
    return [line.strip() for line in value.splitlines() if line.strip()]


def _maybe_float(value: str) -> Optional[float]:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _maybe_int(value: str) -> Optional[int]:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _build_payload(form: Dict[str, str]) -> Dict[str, Any]:
    return {
        "today_date": form.get("today_date") or conductor_schedule._today_string(),
        "sleep_data": {
            "HRV": _maybe_int(form.get("hrv", "")),
            "deep_sleep_hours": _maybe_float(form.get("deep_sleep_hours", "")),
            "duration_hours": _maybe_float(form.get("duration_hours", "")),
        },
        "energy_level": form.get("energy_level") or "unknown",
        "mood": form.get("mood") or "neutral",
        "calendar_events": _list_from_text(form.get("calendar_events", "")),
        "linear_tasks": _list_from_text(form.get("linear_tasks", "")),
        "slack_unreads": _list_from_text(form.get("slack_unreads", "")),
        "notion_version_goals": _list_from_text(form.get("notion_version_goals", "")),
        "blockers": _list_from_text(form.get("blockers", "")),
        "yesterday_expansion_log": _list_from_text(
            form.get("yesterday_expansion_log", "")
        ),
        "health_constraints": {
            "workout": form.get("workout") == "on",
            "deep_sleep_priority": form.get("deep_sleep_priority") == "on",
        },
    }


def _load_sample_payload() -> Dict[str, Any]:
    sample_path = Path(__file__).with_name("sample_schedule_input.json")
    if sample_path.exists():
        with open(sample_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def _build_view(inputs: conductor_schedule.DailyInputs) -> Dict[str, Any]:
    focus = conductor_schedule._core_focus(inputs)
    blocks = conductor_schedule._build_schedule_blocks(inputs)
    return {
        "header": {
            "title": "📅 Chris Daily Rhythm — Generated by Conductor Agent",
            "date": inputs.today_date,
            "version_goals": focus.get("version_goals", []),
            "blockers": focus.get("blockers", []),
            "meta_question": focus.get("meta_question"),
        },
        "blocks": [
            {"title": block.title, "window": block.window, "actions": block.actions}
            for block in blocks
        ],
        "schedule_text": conductor_schedule.generate_schedule(inputs),
    }


@app.route("/", methods=["GET"])
def index():
    sample_payload = _load_sample_payload()
    view = None
    if sample_payload:
        view = _build_view(conductor_schedule.DailyInputs.from_dict(sample_payload))
    return render_template(
        "index.html",
        view=view,
        defaults=sample_payload,
        today_date=conductor_schedule._today_string(),
    )


@app.route("/generate", methods=["POST"])
def generate():
    payload = _build_payload(request.form)
    inputs = conductor_schedule.DailyInputs.from_dict(payload)
    view = _build_view(inputs)
    return render_template(
        "index.html",
        view=view,
        defaults=payload,
        today_date=conductor_schedule._today_string(),
    )


@app.route("/reset", methods=["POST"])
def reset():
    return redirect(url_for("index"))


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)
